# Generated by Django 3.2.25 on 2024-06-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
