# Generated by Django 3.2.25 on 2024-06-10 18:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_mail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='../cgatwxc9v9hkqy4e5kvb', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[800, 800], upload_to='images/'),
        ),
    ]
