# Generated by Django 3.2.25 on 2024-05-20 19:41

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(is_adopted=True, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(is_adopted=False, then=django.db.models.expressions.Value(0)), output_field=models.BooleanField()), '-created_at']},
        ),
    ]
