# Generated by Django 3.2.25 on 2024-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_main_image',
            field=models.BooleanField(default=False),
        ),
    ]
