# Generated by Django 3.2.25 on 2024-03-31 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0003_auto_20240331_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='medias', to='auth.user'),
            preserve_default=False,
        ),
    ]
