# Generated by Django 3.2.25 on 2024-03-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0004_media_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True,
                                    default='../f3hx6euwqexhgg3ehdik',
                                    null=True, upload_to='post_images/'),
        ),
    ]
