# Generated by Django 3.2.25 on 2024-03-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0005_alter_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, default='../f3hx6euwqexhgg3ehdik', upload_to='post_images/'),
        ),
    ]
