# Generated by Django 3.2.25 on 2024-03-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0006_alter_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(
                blank=True,
                null=True,
                storage='cloudinary_storage.storage.VideoMediaCloudinaryStorage',
                upload_to='post_videos/'),
        ),
    ]
