# Generated by Django 3.2.25 on 2024-04-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
        ('posts', '0003_post_dogs'),
        ('medias', '0011_alter_media_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='dogs.dog'),
        ),
        migrations.AlterField(
            model_name='media',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='posts.post'),
        ),
    ]
