# Generated by Django 3.2.25 on 2024-05-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0012_auto_20240402_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, default='../no_image', upload_to='post_images/'),
        ),
    ]
